### ISSUE TITLE
function call warnings...

### ISSUE THREAD

**Issue by protogeezer** [JuliaStats/DataFrames.jl#1115] opened 2016-10-26 17:01 UTC
while experimenting with Gallium, the following potentially consequential warnings were reported:

julia> bp = Gallium.breakpoint("plot_r2_logitudinal.jl",110)
WARNING: both DataArrays and StatsBase export "autocor"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "inverse_rle"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "rle"; uses of it in module DataFrames must be qualified
WARNING: both StatsBase and Distributions export "span"; uses of it in module GLM must be qualified

**Comment by ararslan** [comment] 2016-10-26 17:09
Duplicate of #1094. The problem is with DataArrays, not DataFrames. You're welcome to open an issue there, assuming there isn't already a relevant issue.

**Closed by ararslan** 2016-10-26 17:09 UTC
