### ISSUE TITLE
Can we remove src/RDA.jl?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#955] opened 2016-05-12 17:09 UTC
This code to read a subset of the `.rda` (R data archive) format was used to import saved R `data.frame` objects.  The `RCall` package is much better at this.  I suggest deprecating `read_rda` while doing the conversion for julia v0.5  I believe this will also remove the dependency on the `Gzip`  package.

**Comment by nalimilan** [comment] 2016-05-12 18:51
I was wondering about this too. +1

**Comment by garborg** [comment] 2016-05-13 13:08
I'm for this, too.

The only downside I see is that in [RDatasets.jl](https://github.com/johnmyleswhite/RDatasets.jl), DataFrames with legitimate categorical columns (not just because strings were often pooled in R) are stored as .rda files.

Maybe move the file into RDatasets.jl in the short term and move those files to feather or .jld longer term? c.c. @johnmyleswhite

**Comment by nalimilan** [comment] 2016-05-13 13:37
At the very least, we could move `read_rda` to RDatasets waiting for a larger refactoring.

**Comment by johnmyleswhite** [comment] 2016-05-15 02:42
+1

**Comment by nalimilan** [comment] 2016-05-15 06:56
See also https://github.com/JuliaStats/DataFrames.jl/issues/958, which moving to RCall.jl would likely fix.

**Comment by ararslan** [comment] 2016-07-20 17:19
@alyst What's the state of your RData package? Is it such that it could remove the RDA stuff in here entirely and direct users to your package?

For the others, see https://github.com/alyst/RData.jl

**Comment by alyst** [comment] 2016-07-20 21:19
@ararslan I'm using it regularly and it works for me. It's an extended version of `DataFrames.read_rda()` that supports all R data types (so it does not crash on an arbitrary RData file, although not every R type is converted to Julia counterpart). So, yes, I think you can recommend it to the users. I suspect the first users might run into issues, because `RData` received limited testing so far, but I will try to fix the bugs as they are discovered.

**Comment by nalimilan** [comment] 2016-07-20 21:39
Great. So let's deprecate RDA.jl ASAP in favor of RData.jl. A good stress test for it is porting RDatasets.jl and checking that all data sets can be loaded correctly.

**Comment by ararslan** [comment] 2016-07-20 21:40
First RData needs to be registered in METADATA. Should also set up Travis and coverage.

**Comment by ararslan** [comment] 2016-07-21 00:06
@alyst If you want you could transfer ownership of RData.jl to the JuliaStats organization for more rapid development and maintenance, but that's totally up to you.

**Comment by alyst** [comment] 2016-07-21 12:06
@ararslan If you think that making `RData` a part of JuliaStats would be beneficial for the community, I am all for it. Is there anything required from my side?

**Comment by ararslan** [comment] 2016-07-21 18:48
It would make sense to me to have it under the JuliaStats umbrella but I'd be interested to hear what others think. On your end you'd have to go to the repo settings and transfer ownership.

**Comment by ararslan** [comment] 2016-08-08 20:42
Bump. @alyst, are you still considering transferring ownership of RData.jl to JuliaStats?

**Comment by alyst** [comment] 2016-08-08 20:58
@ararslan Yes I am, whenever JuliaStats "stakeholders" decide it's worth it.

**Comment by ararslan** [comment] 2016-08-08 21:24
Sounds like myself and @nalimilan think it's worth it (based on his thumbs up). What do the other folks think?

**Comment by quinnj** [comment] 2016-08-08 22:24
+1

**Comment by ararslan** [comment] 2016-08-09 21:31
@alyst By show of thumbs (and Jacob), it looks like people are thinking it's worth it. 😄

**Comment by alyst** [comment] 2016-08-11 22:13
@ararslan Great! I've tried to transfer `RData.jl` to JuliaStats, but got an error saying that I'm not an admin of JuliaStats to make the transfer. I've never transferred repos before, so I don't know whether JuliaStats admins have received notifications about pending transfer and can complete it, or there is no other way than to make me an admin temporarily.

**Comment by johnmyleswhite** [comment] 2016-08-11 22:51
@alyst: You have the necessary permissions now.

**Comment by alyst** [comment] 2016-08-11 23:41
I've just transferred the repo. Have fun!

**Comment by ararslan** [comment] 2016-08-11 23:42
Thanks @alyst!

**Comment by ararslan** [comment] 2016-08-11 23:48
Can an owner set the RData permissions so that JuliaStats members have our usual permissions? When doing transfers on GitHub the permissions are copied over too, so regular members don't currently have commit access.

**Comment by alyst** [comment] 2016-08-11 23:52
@ararslan I've just added the same permissions as `DataFrames.jl`

**Comment by ararslan** [comment] 2016-08-11 23:56
For some reason I'm not able to enable Travis CI on it. I've been able to do it with other repos... not sure what the issue is.

**Comment by alyst** [comment] 2016-08-12 00:00
@ararslan TravisCI needs to be enabled in the settings (currently it's not), but since it requires some configuration, it's better that the more experienced admins set it up.

**Comment by alyst** [comment] 2016-08-21 10:11
RData package is now registered

**Closed** 2016-08-31 16:58 UTC
Labels: decision
