### ISSUE TITLE
formula & statsmodel code needs more testing

### ISSUE THREAD

**Issue by garborg** [JuliaStats/DataFrames.jl#786] opened 2015-03-19 18:34 UTC
While the code is impressive, it is to me, pretty opaque. The last couple times I've dipped into it for maintenance purposes, I've wanted to get aggressive tightening it up, readability- (make it more inviting to audit and contribute to), logic-, and performance-wise, but it (at least) seems easy to break without triggering test failures. 

`formula.jl` has decent (but improvable) test coverage stats, but I'd love it if both it and `statsmodels.jl` were tested more exhaustively -- some functions are completely untested, but it looks mostly like more's needed in terms of data types, model complexity, and interaction types. 

Hoping someone who's worked on the code, or used a broad chunk of it steps up. cc. @kleinschmidt, @dmbates, @simonster, @timema

**Comment by simonster** [comment] 2015-03-19 19:10
I admit it's pretty opaque to me too. In #550 @johnmyleswhite said he was working on a rewrite of the Formula code. I also commented a bit on implementation there.

**Comment by johnmyleswhite** [comment] 2015-03-19 19:12
I got about 50% of the way through rewriting this, but haven't touch that work in a long time. I strongly agree that the code is pretty opaque as is. What I found helpful was to start rewriting things in terms of explicit lowering steps that transform formulas into simpler forms.

**Comment by johnmyleswhite** [comment] 2015-03-19 19:13
I keep pushing on trying to standardize the semantics of formulas. I think if we did that, it would be a lot easier to make progress on this since we could write out obvious tests for how things like interactions should work.

**Comment by garborg** [comment] 2015-03-19 19:25
@johnmyleswhite That sounds right (standardizing the semantics).

**Comment by johnmyleswhite** [comment] 2015-03-19 19:33
The main complications as I understand them are:

* Are intercepts always explicit?
* Does `(a)*(b)` lower to `(a) + (b) + (a)&(b)`?
* How are higher-order interactions parsed and what semantics are they given? What is `a * (b * c)`? The previous claim suggests that it's `a + (b * c) + a&(b * c)`, which is `a + b + c + b&c + a&(b + c + b&c)`, which is `a + b + c + b&c + a&b + a&c + a&b&c`. If this is the correct interpretation, then you should get the full semantics out of this case, although you may still need some weird re-ordering operations.

**Comment by kleinschmidt** [comment] 2015-03-19 22:21
That's more or less the semantics interaction terms have in R, as far as I can tell. The only complication is the ordering, like you allude to, which is why I wrote the lowering of a*b to be a + (a&b) + b (plus later sorting by interaction order once everything is lowered). That makes the ordering of the two-way interaction terms match that in R, but it's mostly cosmetic. E.g., a*b*c goes to a + b + c + a&b + a&c + b&c + a&b&c. 

(please pardon my thumb-typing)

--
dave.f.kleinschmidt@gmail.com
www.bcs.rochester.edu/people/dkleinschmidt/
413-884-2741

**Comment by kleinschmidt** [comment] 2015-03-19 22:26
I should add I'm happy to work on either cleaning up the existing code and adding tests or working on a rewrite if you want a hand @johnmyleswhite. But having a clear plan on what we want the semantics to be is a necessary first step.

My impression is that consensus is growing behind always explicit intercepts. Despite the fact that this will alienate some R users it seems to me it will make it easier to explain, document, and implement the formulas interface.

(please pardon my thumb-typing)

--
dave.f.kleinschmidt@gmail.com
www.bcs.rochester.edu/people/dkleinschmidt/
413-884-2741

**Comment by johnmyleswhite** [comment] 2015-03-20 00:12
I certainly would prefer explicit intercepts.

Another set of issues I'd like to see addressed: different matrix representations. For example, I'd like to see support for:

* Generating a design matrix without an intercept column and optionally with an intercept column
* Generating a design matrix that mixes a few dense columns with many sparse columns
* Mutating an existing design matrix based on a new DataFrame

**Comment by kleinschmidt** [comment] 2015-03-20 00:21
Now that I've looked back at #550, I'm a little confused.  What exactly is it that's not working for higher-order interactions?  As far as I can tell model matrices are generated just fine for formulas like `y ~ x1 * x2 * x3 + x4 * x5 * x6`.

**Comment by johnmyleswhite** [comment] 2015-03-20 00:24
I don't think anything's wrong. I just want to make sure we all agree those are the right semantics.

**Comment by kleinschmidt** [comment] 2015-03-20 01:05
Ah, turns out I was more deeply confused than I thought: it's 2015, not 2014, and #550 is a year old at this point.  I think the next step is get (enough) people to agree on the semantics of formulas.  I think the only really contentious thing here is the intercept, which has been debated in various places.  In the mean time, I'm going to go through the formulas.jl source, add tests to bring up the coverage, comment the code that's already there, and at least re-write some of the more opaque code to have less `aa`s etc.

**Comment by kleinschmidt** [comment] 2015-03-20 01:14
Part of the reason that the coverage of statsmodels.jl is so abysmal is that most of the code that might touch it is in GLM.jl (where there are some tests for code that's marked as not covered, like `fit` and `predict`).  Is it kosher to have tests in DataFrames.jl that depend on GLM.jl?

**Comment by johnmyleswhite** [comment] 2015-03-20 03:35
I think it'd better to avoid that if possible. It seems like there's no reason you need GLM to assess whether formula parsing and model matrix construction work correctly.

**Comment by simonster** [comment] 2015-03-20 03:41
Yes, ideally we'd create a dummy RegressionModel type for testing purposes.

**Comment by johnmyleswhite** [comment] 2015-03-20 15:23
More comments on this: one of my long-term goals is to enable GLM modeling from a database without passing through an intermediate DataFrame. So it would be great to make the model matrix construction generic enough that it doesn't depend on the internal representation of things like `PooledDataVector`.

**Comment by kleinschmidt** [comment] 2015-06-13 22:02
Coverage for statsmodel.jl is now 100%, and formula.jl is 90%.  That addresses the testing issue, at least, if not the clarity of the underlying code.  So let's close this issue, and open a new one as needed to organize discussion about the specification of the formula DSL and how it's implemented.

**Closed by kleinschmidt** 2015-06-13 22:02 UTC
