### ISSUE TITLE
finding duplicated values in colums

### ISSUE THREAD

**Issue by mkborregaard** [JuliaStats/DataFrames.jl#908] opened 2016-02-05 13:38 UTC
I very often need to extract the values of one or more columns from a DataFrame based on whether the value of one or more columns is similar. So if I have a DataFrame X with:
```
| site | foo | bar |
| "a"  |  1  |  1  |
| "a"  |  1  |  2  |
| "b"  |  2  |  3  |
```
In this case, the bar values are redundant, and each site value is always associated with the same foo value. I want a DataFrame that matches site to foo values and discards bar values.
In R I would do:
```
ret <- X[!duplicated(X$site), c(["site", "foo"]]
```
which would give
```
| site | foo | 
| "a"  |  1  |  
| "b"  |  2  |  
```

But in julia, the `nonunique(df)` function only accepts a full DataFrame, leading to ugly code like
```
ret = X[!nonunique(DataFrame(tmp = X[:site]), [:site, :foo]]
```

Could the `nonunique` function, or the `drop_duplicates!`referred to here #363 (but which I could not find) be embellished a little to allow flexibility in the definition of uniques?

Thanks!

**Comment by alyst** [comment] 2016-02-05 13:50
You can also do
```
ret = X[!nonunique(X[:,[:site]]), [:site, :foo]]
```
which is as "ugly" as R equivalent.

**Comment by mkborregaard** [comment] 2016-02-05 14:10
I guess you are right, though I am not too keen on the `[:,[:` idiom. I would prefer a second optional argument to unique and nonunique that let me specify the rows to compare, though.

**Comment by nalimilan** [comment] 2016-02-05 14:12
This is essentially a duplicate of https://github.com/JuliaStats/DataFrames.jl/issues/363. The `drop_duplicates!` mentioned there is called `unique!` now AFAIK. It would be nice to allow passing the names of columns to take into account to that function, which should fill your needs with a nicer syntax than R.

Closing this report, but feel free to comment on the other one.

**Closed by nalimilan** 2016-02-05 14:12 UTC
