### ISSUE TITLE
Warnings (ambiguous getindex)

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/DataFrames.jl#765] opened 2015-02-09 18:20 UTC
Latest Julia:

```julia
using DataFrames
```

>Warning: New definition 
    getindex(DataArrays.DataArray{T,N},Union(AbstractArray{T,1},Real)...) at /home/julio/.julia/v0.4/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(DataArrays.AbstractDataArray{T,N},Real) at /home/julio/.julia/v0.4/DataArrays/src/indexing.jl:104.
To fix, define 
    getindex(DataArrays.DataArray{T,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.DataArray{T,N},Union(AbstractArray{T,1},Real)...) at /home/julio/.julia/v0.4/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(AbstractArray{T,N},Real) at abstractarray.jl:435.
To fix, define 
    getindex(DataArrays.DataArray{T,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Union(AbstractArray{T,1},Real)...) at /home/julio/.julia/v0.4/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(DataArrays.AbstractDataArray{T,N},Real) at /home/julio/.julia/v0.4/DataArrays/src/indexing.jl:104.
To fix, define 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Union(AbstractArray{T,1},Real)...) at /home/julio/.julia/v0.4/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(AbstractArray{T,N},Real) at abstractarray.jl:435.
To fix, define 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Real)
before the new definition.
Warning: using DataFrames.describe in module Main conflicts with an existing identifier.

**Comment by juliohm** [comment] 2015-02-09 18:28
This warning is probably causing a serious error:

```julia
df = DataFrame(x=[1,2,3],y=[4.,5.,6.])
df[:x,:y]
```

>ERROR: MethodError: `getindex` has no method matching getindex(::DataFrames.DataFrame, ::Symbol, ::Symbol)
Closest candidates are:
  getindex(::DataFrames.DataFrame, ::Real, ::Union(Symbol,Real))
  getindex(::DataFrames.DataFrame, ::Union(Symbol,Real))
  getindex{T<:Real}(::DataFrames.DataFrame, ::AbstractArray{T<:Real,1}, ::Union(Symbol,Real))
  ...

**Comment by tshort** [comment] 2015-02-09 18:51
The `getindex` error message is not related to the warnings. It's telling you that your indexing method is incorrect. If you meant to select two columns, you can do that with:

```julia
df[ [:x, :y] ]
```
The extra brackets pass a vector of symbols to getindex.

**Comment by tshort** [comment] 2015-02-09 18:53
Also, those method ambiguities are in the [DataArrays package](https://github.com/JuliaStats/DataArrays.jl).

**Comment by juliohm** [comment] 2015-02-09 18:58
@tshort, I was able to use `df[1:10,[:x,:y]]` before the latest pull, now it doesn't work.

What is the correct way of querying these ranges in a dataframe now?

**Comment by tshort** [comment] 2015-02-09 19:20
It works for me:

```julia
julia> d = DataFrame(a = rand(1:10,20), x = rand(20), y = rand(20));

julia> d[1:10, [:x,:y]]
10x2 DataFrame
| Row | x         | y         |
|-----|-----------|-----------|
| 1   | 0.649857  | 0.557144  |
| 2   | 0.57126   | 0.361365  |
| 3   | 0.676964  | 0.91767   |
| 4   | 0.0734608 | 0.0769796 |
| 5   | 0.676981  | 0.47995   |
| 6   | 0.688151  | 0.0860809 |
| 7   | 0.844548  | 0.166854  |
| 8   | 0.878062  | 0.457129  |
| 9   | 0.719522  | 0.0969891 |
| 10  | 0.927068  | 0.5675    |
```

**Comment by juliohm** [comment] 2015-02-09 19:26
This is the error I get:

>ERROR: UndefVarError: I_1 not defined
 in anonymous at /home/julio/.julia/v0.4/DataArrays/src/indexing.jl:30
 in _getindex at /home/julio/.julia/v0.4/DataArrays/src/indexing.jl:141
 in getindex at /home/julio/.julia/v0.4/DataArrays/src/indexing.jl:152
 in getindex at /home/julio/.julia/v0.4/DataFrames/src/dataframe/dataframe.jl:239

and the version I'm using:

>Julia Version 0.4.0-dev+3230
Commit 83bbfe4* (2015-02-09 16:47 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tshort** [comment] 2015-02-09 19:28
Is that with the same example I just gave? If not, please provide a
reproducible example.

**Comment by juliohm** [comment] 2015-02-09 19:34
Yes, the same example.

**Comment by tshort** [comment] 2015-02-09 19:37
Looks like a bug. I don't have your setup handy. I recommend closing this
issue. Then open a new issue with that example and your result.

**Comment by simonster** [comment] 2015-02-09 19:37
This is fallout from JuliaLang/julia#9098 in DataArrays. I'm working on it, but I may need @timholy's help.

**Comment by simonster** [comment] 2015-02-09 22:26
Should be fixed by JuliaLang/Compat.jl#42

**Closed by simonster** 2015-02-09 22:26 UTC
