### ISSUE TITLE
apply_type error in RDA code

### ISSUE THREAD

**Issue by tshort** [JuliaStats/DataFrames.jl#756] opened 2015-01-04 12:59 UTC
In Julia 0.3.3, I get the following on Arch Linux:

```julia
julia> using DataFrames
ERROR: type: apply_type: in RSEXPREC, expected Int64, got Uint8
 in include_3B_211 at /usr/bin/../lib/julia/sys.so
 in include_from_node1_3B_1800 at /usr/bin/../lib/julia/sys.so
 in anonymous at no file:109
 in include_3B_211 at /usr/bin/../lib/julia/sys.so
 in include_from_node1_3B_1800 at /usr/bin/../lib/julia/sys.so
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/tshort/.julia/v0.3/DataFrames/src/RDA.jl, in expression starting on line 82
while loading /home/tshort/.julia/v0.3/DataFrames/src/DataFrames.jl, in expression starting on line 78
```
It works fine on Julia 0.4-dev on the same machine. Commit 6230bd3 worked.

**Comment by garborg** [comment] 2015-01-04 23:25
@alyst, looks like this worked the commit before #754 -- think you can guess what the issue is or would you need more info?

**Comment by alyst** [comment] 2015-01-05 18:51
The line in question is
```julia
type RSymbol <: RSEXPREC{0x01}   # Not quite the same as a Julia symbol
```
I wonder whether the issue was fixed in julia 0.3.4 (JuliaLang/julia/issues/9161), because the Travis builds are passing. @tshort, could you please try 0.3.4?

**Comment by tshort** [comment] 2015-01-05 19:00
Good timing. The Arch package was updated today to 0.3.4, and the error's gone! Sorry for bothering you.

**Comment by garborg** [comment] 2015-01-05 19:06
Thanks for looking into it, both of you.

**Closed by garborg** 2015-01-05 19:06 UTC
