### ISSUE TITLE
groupby() and InexactError

### ISSUE THREAD

**Issue by tcovert** [JuliaStats/DataFrames.jl#960] opened 2016-05-16 15:40 UTC
The current version of groupby() encounters an InexactError on line 101 of grouping.jl under the following conditions:
(1) The grouping variables are already PooledDataVectors
(2) The size of the "refs" type for some of already-pooled grouping variables is small, say, 16 bit Uint
(3) There are enough unique groups among the grouping variables to overflow 16 bits of space

Here is an MWE: https://gist.github.com/tcovert/8770785387018a2590505bb0087cda21

My guess is that the issue actually arises in line 93, where "x" is created.  It will probably get an eltype which is too small.

The work around for this is to undo the pooling, and add back later as needed, but I assume that this is not the intended design.

**Comment by johnmyleswhite** [comment] 2016-05-16 16:03
I continue to believe that parametric pooling is a mistake: we would be better off optimizing for 32-bit or 64-bit pools than in trying to make things minimally sized. This kind of bug suggests the current design isn't correctly implemented.

But fixing that issue would have to be addressed in DataArrays.

**Comment by nalimilan** [comment] 2016-05-16 16:49
This looks like an issue in DataFrames. Indeed, it's incorrect to assume that the crossing of two PDAs will fit in the same integer size as the first PDA.  See https://github.com/JuliaStats/DataFrames.jl/pull/961.

**Closed** 2016-05-19 17:58 UTC

**Comment by tcovert** [comment] 2016-06-09 19:22
The same InexactError() can show up in line 92 of abstractdataframe/join.jl, where a new, possibly-too-small PDA is created using the pooling types of the existing PDA's.  Presumably, a fix similar to the one in #961 will solve this problem as well.

**Comment by nalimilan** [comment] 2016-06-09 21:20
Could you provide a simpler reproducer?

**Comment by tcovert** [comment] 2016-06-10 15:30
I think this shows it in action:

https://gist.github.com/tcovert/59644b01465d2e6bfe80ace1a453bbca

**Comment by nalimilan** [comment] 2016-06-10 17:37
Thanks. I have another fix at https://github.com/JuliaStats/DataFrames.jl/pull/993.

**Comment by tcovert** [comment] 2016-06-10 17:57
Great.  Also, I just did a quick search for ".refs" in the DataFrames codebase and did not see any additional issues.
