### ISSUE TITLE
Warning: Method definition `describe` overwritten

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/DataFrames.jl#1184] opened 2017-05-04 15:41 UTC
```julia
using DataFrames
```
>WARNING: Method definition describe(AbstractArray) in module StatsBase at /home/juliohm/.julia/v0.5/StatsBase/src/scalarstats.jl:573 overwritten in module DataFrames at /home/juliohm/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:407.

**Comment by nalimilan** [comment] 2017-05-04 15:57
We'll need something equivalent to https://github.com/JuliaData/DataTables.jl/pull/57. Cc: @cjprybol

**Comment by cjprybol** [comment] 2017-05-04 17:16
just opened the PRs, thanks @juliohm!

**Comment by zwolfe21** [comment] 2017-05-17 19:23
I started getting this error when I ran Pkg.update() and found it when I tried using Gadfly. Just curious about the error and how I fix it.

**Comment by cjprybol** [comment] 2017-05-18 00:24
In https://github.com/JuliaStats/DataFrames.jl/pull/1185 we decided that the best way to fix this would be to drop Julia 0.5 support. https://github.com/JuliaStats/DataFrames.jl/pull/1186 has the code to drop Julia 0.5, and once that is merged then I need to modify https://github.com/JuliaStats/DataFrames.jl/pull/1185 and rebase it onto the changes introduced by https://github.com/JuliaStats/DataFrames.jl/pull/1186. If you'd be interested in forking https://github.com/JuliaStats/DataFrames.jl/pull/1186 to help debug the Travis errors, @zwolfe21, that could help speed this along! If not, we know the fix and should have it finished soon, but help is always welcome!

**Comment by cjprybol** [comment] 2017-05-18 19:02
#1186 and #1185 have been merged so this should be resolved by a `Pkg.checkout("DataFrames")` to get the latest master right now, and should be fixed by `Pkg.update()` upon the next version release.

**Comment by alexeypetrushin** [comment] 2017-06-06 13:18
Same issue

**Comment by cjprybol** [comment] 2017-06-06 19:56
@alexeypetrushin are you running Julia 0.5 or the 0.6 release candidates? As stated above, the fix was pushed after a commit that removed Julia 0.5 support, so this issue will persist in 0.5 but I can't reproduce this in 0.6.

**Comment by alexeypetrushin** [comment] 2017-06-13 10:48
Got it, thanks, I was using Julia 0.5X.

**Closed** 2017-06-13 11:37 UTC

**Comment by samoconnor** [comment] 2017-06-20 22:26
I found that `Pkg.pin("StatsBase", v"0.13.1")` resolved the problem using Julia 0.5.2.
